/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Ninja({ action, rotation, ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('./white_ninja.glb');
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		let currentAction = actions[action];

		if (currentAction) {
			currentAction.reset().fadeIn(0.25).play();
		}

		return () => {
			if (currentAction) {
				setTimeout(() => {
					currentAction.fadeOut(0.24).stop();
				}, 100); // Adjust the timing as necessary
			}
		};
	}, [action, actions]);

	return (
		<group
			position={[0, -1, 0]}
			rotation={rotation}
			ref={group}
			{...props}
			dispose={null}
		>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					rotation={[-Math.PI / 2, 0, 0]}
				>
					<group name="root">
						<group
							name="GLTF_SceneRootNode"
							rotation={[Math.PI / 2, 0, 0]}
						>
							<group name="_155">
								<group name="all_154">
									<group
										name="leftLeg_15"
										position={[0.125, 0.75, 0]}
									>
										<group
											name="d54c1edd-755b-8942-bfbb-d0888a3ae66c_0"
											position={[-0.125, -0.75, 0]}
										>
											<mesh
												name="Object_7"
												castShadow
												receiveShadow
												geometry={nodes.Object_7.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="d851fde1-ac3a-6503-e302-e92936af1ec1_1"
											position={[-0.063, -1, 0.063]}
										>
											<mesh
												name="Object_9"
												castShadow
												receiveShadow
												geometry={nodes.Object_9.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="b5cf5f8b-ea4e-631f-a45f-6ce4939235a5_2"
											position={[-0.063, -1, 0.063]}
										>
											<mesh
												name="Object_11"
												castShadow
												receiveShadow
												geometry={nodes.Object_11.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="2a195605-1a07-33b1-d065-5d7c05c1c3a5_3"
											position={[-0.063, -1, -0.078]}
										>
											<mesh
												name="Object_13"
												castShadow
												receiveShadow
												geometry={nodes.Object_13.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="98f84776-6859-3fa4-3efe-4559fa28e78f_4"
											position={[-0.203, -1, 0.063]}
										>
											<mesh
												name="Object_15"
												castShadow
												receiveShadow
												geometry={nodes.Object_15.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="2616f545-d59d-0f67-1948-830a2b67d99f_5"
											position={[-0.016, -0.156, -0.07]}
											rotation={[0, 0, Math.PI / 8]}
										>
											<mesh
												name="Object_17"
												castShadow
												receiveShadow
												geometry={nodes.Object_17.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="0d685689-e577-5e41-0b04-2fa4b2bd6ec8_6"
											position={[-0.063, -1.094, 0.063]}
										>
											<mesh
												name="Object_19"
												castShadow
												receiveShadow
												geometry={nodes.Object_19.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="3e15b17f-c3bb-6414-0b05-79c6ece451ad_7"
											position={[-0.07, -0.166, -0.003]}
											rotation={[-Math.PI / 8, 0, 0]}
										>
											<mesh
												name="Object_21"
												castShadow
												receiveShadow
												geometry={nodes.Object_21.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c6953d8b-02b3-10ad-cbc1-87959e93059d_8"
											position={[-0.063, -1.094, 0.063]}
										>
											<mesh
												name="Object_23"
												castShadow
												receiveShadow
												geometry={nodes.Object_23.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c6c93e49-7412-547b-45c5-ae61366faa90_9"
											position={[0.069, -0.234, -0.07]}
											rotation={[0, 0, Math.PI / 8]}
										>
											<mesh
												name="Object_25"
												castShadow
												receiveShadow
												geometry={nodes.Object_25.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c1ae1b57-e739-9b96-ab54-8a5efc40a50e_10"
											position={[-0.063, -1.188, 0.063]}
										>
											<mesh
												name="Object_27"
												castShadow
												receiveShadow
												geometry={nodes.Object_27.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="269b57f1-aaec-9315-7ad4-f41baa322ab7_11"
											position={[-0.07, -0.297, -0.069]}
											rotation={[Math.PI / 8, 0, 0]}
										>
											<mesh
												name="Object_29"
												castShadow
												receiveShadow
												geometry={nodes.Object_29.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="leftLeg1_14"
											position={[0, -0.375, 0]}
										>
											<group
												name="a7893870-4cec-9058-ee0f-6b300a6ae4f9_12"
												position={[-0.125, -0.375, 0]}
											>
												<mesh
													name="Object_32"
													castShadow
													receiveShadow
													geometry={nodes.Object_32.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="cb4e9767-c389-2aa5-0137-7ef170d01fb7_13"
												position={[-0.069, 0.016, 0.07]}
												rotation={[0, 0, -Math.PI / 8]}
											>
												<mesh
													name="Object_34"
													castShadow
													receiveShadow
													geometry={nodes.Object_34.geometry}
													material={materials.material_0}
												/>
											</group>
										</group>
									</group>
									<group
										name="rightLeg_19"
										position={[-0.125, 0.75, 0]}
									>
										<group
											name="021c282e-5c27-3ce1-065b-37f6093788cb_16"
											position={[0.125, -0.75, 0]}
										>
											<mesh
												name="Object_37"
												castShadow
												receiveShadow
												geometry={nodes.Object_37.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="rightLeg1_18"
											position={[0, -0.375, 0]}
										>
											<group
												name="4f9e96ed-dbd2-a33a-dc7a-ccafea5a9f74_17"
												position={[0.125, -0.375, 0]}
											>
												<mesh
													name="Object_40"
													castShadow
													receiveShadow
													geometry={nodes.Object_40.geometry}
													material={materials.material_0}
												/>
											</group>
										</group>
									</group>
									<group
										name="h_head_49"
										position={[0, 1.5, 0]}
									>
										<group
											name="f90e509b-65e9-7446-b594-08fa3b2df695_20"
											position={[0, -1.5, 0]}
										>
											<mesh
												name="Object_43"
												castShadow
												receiveShadow
												geometry={nodes.Object_43.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="60cab54e-70b7-fd6c-5418-c62e92441126_21"
											position={[0, -0.938, -0.281]}
										>
											<mesh
												name="Object_45"
												castShadow
												receiveShadow
												geometry={nodes.Object_45.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="24c2ca2e-8041-64f3-9059-f7c279f199ec_22"
											position={[0, -0.859, -0.281]}
										>
											<mesh
												name="Object_47"
												castShadow
												receiveShadow
												geometry={nodes.Object_47.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c87e6bfd-c6e8-e20c-7fd0-b7bced6129b0_23"
											position={[0, -0.938, -0.219]}
										>
											<mesh
												name="Object_49"
												castShadow
												receiveShadow
												geometry={nodes.Object_49.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="696e2154-c581-fa71-61e1-4e32fac733fb_24"
											position={[0, -0.859, -0.219]}
										>
											<mesh
												name="Object_51"
												castShadow
												receiveShadow
												geometry={nodes.Object_51.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="f9cb385d-5da4-51c9-6366-87479cc5f7b2_25"
											position={[0, -0.703, -0.219]}
										>
											<mesh
												name="Object_53"
												castShadow
												receiveShadow
												geometry={nodes.Object_53.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="6e476176-4b7a-f141-9905-87170a35e5b5_26"
											position={[0, -0.781, -0.219]}
										>
											<mesh
												name="Object_55"
												castShadow
												receiveShadow
												geometry={nodes.Object_55.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="a8559e18-cf44-998c-70d6-c772b00d2c3d_27"
											position={[0, -0.55, -0.219]}
										>
											<mesh
												name="Object_57"
												castShadow
												receiveShadow
												geometry={nodes.Object_57.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="50d6e498-6c62-e32a-4996-ff41a21f7103_28"
											position={[0, -0.472, -0.219]}
										>
											<mesh
												name="Object_59"
												castShadow
												receiveShadow
												geometry={nodes.Object_59.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="72aa5738-ecd7-6420-46e0-d19d6aca5518_29"
											position={[0, -0.628, -0.219]}
										>
											<mesh
												name="Object_61"
												castShadow
												receiveShadow
												geometry={nodes.Object_61.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="83b71b14-3710-0a41-f08e-31df55d0185d_30"
											position={[-0.516, -0.472, -0.219]}
										>
											<mesh
												name="Object_63"
												castShadow
												receiveShadow
												geometry={nodes.Object_63.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="b4326dee-3fa4-85ec-079f-afd6b2701868_31"
											position={[-0.516, -0.55, -0.219]}
										>
											<mesh
												name="Object_65"
												castShadow
												receiveShadow
												geometry={nodes.Object_65.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="08bd0643-642f-5717-f248-de665bca1186_32"
											position={[-0.516, -0.628, -0.219]}
										>
											<mesh
												name="Object_67"
												castShadow
												receiveShadow
												geometry={nodes.Object_67.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="85840d3b-6556-d9f4-4891-85c620317bc7_33"
											position={[-0.516, -0.703, -0.219]}
										>
											<mesh
												name="Object_69"
												castShadow
												receiveShadow
												geometry={nodes.Object_69.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="0cf491e0-dda7-8869-1ec7-d6a5f268a863_34"
											position={[-0.516, -0.781, -0.219]}
										>
											<mesh
												name="Object_71"
												castShadow
												receiveShadow
												geometry={nodes.Object_71.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="5ed4cf76-2e98-6bf3-6d2d-cde514f6881e_35"
											position={[-0.516, -0.859, -0.219]}
										>
											<mesh
												name="Object_73"
												castShadow
												receiveShadow
												geometry={nodes.Object_73.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="64cf6a84-3a21-af0c-ba62-6bcc7ef24cd7_36"
											position={[-0.516, -0.938, -0.219]}
										>
											<mesh
												name="Object_75"
												castShadow
												receiveShadow
												geometry={nodes.Object_75.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="03f88ea8-21b1-f4d8-5f97-5fcb5b100cac_37"
											position={[0, -0.609, -0.281]}
										>
											<mesh
												name="Object_77"
												castShadow
												receiveShadow
												geometry={nodes.Object_77.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="b0b4004c-2a73-61e3-9dd6-0344c05da32b_38"
											position={[0, -0.688, -0.281]}
										>
											<mesh
												name="Object_79"
												castShadow
												receiveShadow
												geometry={nodes.Object_79.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="e4407a15-507f-999c-c9e6-c25494f0fa44_39"
											position={[0, -0.484, -0.281]}
										>
											<mesh
												name="Object_81"
												castShadow
												receiveShadow
												geometry={nodes.Object_81.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="3f3928c8-e139-1539-3319-eb4bf4c7c637_40"
											position={[0, -0.563, -0.281]}
										>
											<mesh
												name="Object_83"
												castShadow
												receiveShadow
												geometry={nodes.Object_83.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c19283e3-53cf-4223-0ac6-51370c4e8a5d_41"
											position={[0, -0.688, 0.234]}
										>
											<mesh
												name="Object_85"
												castShadow
												receiveShadow
												geometry={nodes.Object_85.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="f8fc3b65-6036-7780-b7ce-69ab4681b86f_42"
											position={[0, -0.609, 0.234]}
										>
											<mesh
												name="Object_87"
												castShadow
												receiveShadow
												geometry={nodes.Object_87.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="248acd82-ef4b-52e4-f202-4a9990dd082f_43"
											position={[0, -0.563, 0.234]}
										>
											<mesh
												name="Object_89"
												castShadow
												receiveShadow
												geometry={nodes.Object_89.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="43ee6475-97dc-eb5c-d4af-6ae1a315253a_44"
											position={[0, -0.484, 0.234]}
										>
											<mesh
												name="Object_91"
												castShadow
												receiveShadow
												geometry={nodes.Object_91.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="caf0f745-7417-e545-06d2-5dec1c8a859a_45"
											position={[0, -0.938, 0.234]}
										>
											<mesh
												name="Object_93"
												castShadow
												receiveShadow
												geometry={nodes.Object_93.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="bf162709-8b83-f54e-16de-2fe09aae9ffb_46"
											position={[0, -0.766, 0.234]}
										>
											<mesh
												name="Object_95"
												castShadow
												receiveShadow
												geometry={nodes.Object_95.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="b5af6a10-59ca-7542-4d99-351acf72827d_47"
											position={[0, -0.844, 0.234]}
										>
											<mesh
												name="Object_97"
												castShadow
												receiveShadow
												geometry={nodes.Object_97.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="b15a5b93-405d-b177-0845-cd4844749e5f_48"
											position={[0, -0.484, 0.172]}
										>
											<mesh
												name="Object_99"
												castShadow
												receiveShadow
												geometry={nodes.Object_99.geometry}
												material={materials.material_0}
											/>
										</group>
									</group>
									<group
										scale={1}
										name="body_153"
										position={[0, 1.5, 0]}
									>
										<group
											name="a84abc0c-8e8c-0d48-e0ef-a6d7efbe367f_50"
											position={[0, -1.5, 0]}
										>
											<mesh
												scale={1.1}
												name="Object_102"
												castShadow
												receiveShadow
												geometry={nodes.Object_102.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="e2d63aed-9557-001a-2dfc-bbc3ec1b8888_51"
											position={[0, -1.688, 0.125]}
										>
											<mesh
												name="Object_104"
												castShadow
												receiveShadow
												geometry={nodes.Object_104.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="87c14ea7-bed5-559b-8c77-2e3b2f8830ca_52"
											position={[0, -1.688, 0.125]}
										>
											<mesh
												name="Object_106"
												castShadow
												receiveShadow
												geometry={nodes.Object_106.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c136d13c-60f2-a973-b31c-1bfc30bd042f_53"
											position={[0.531, -1.688, 0.125]}
										>
											<mesh
												name="Object_108"
												castShadow
												receiveShadow
												geometry={nodes.Object_108.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c0a14088-4b78-007e-28d6-3606a9fdbfa9_54"
											position={[0, -1.688, -0.156]}
										>
											<mesh
												name="Object_110"
												castShadow
												receiveShadow
												geometry={nodes.Object_110.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="94d4f95c-5d07-0634-181a-6595b2268ca4_55"
											position={[0, -1.625, 0.125]}
										>
											<mesh
												name="Object_112"
												castShadow
												receiveShadow
												geometry={nodes.Object_112.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="568058ee-12f2-23b5-3200-6750fa87c920_56"
											position={[0.469, -1.75, 0.125]}
										>
											<mesh
												name="Object_114"
												castShadow
												receiveShadow
												geometry={nodes.Object_114.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="159dfd72-ea89-4cee-7040-a2a4fe6378f8_57"
											position={[0.406, -1.75, 0.125]}
										>
											<mesh
												name="Object_116"
												castShadow
												receiveShadow
												geometry={nodes.Object_116.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="a70780b4-ddc0-66c8-9c9d-0756e32f0c16_58"
											position={[0.344, -1.75, 0.125]}
										>
											<mesh
												name="Object_118"
												castShadow
												receiveShadow
												geometry={nodes.Object_118.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="c8922655-3cdd-07d4-9f86-3849289b8c4d_59"
											position={[0.281, -1.75, 0.125]}
										>
											<mesh
												name="Object_120"
												castShadow
												receiveShadow
												geometry={nodes.Object_120.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="f89548c9-ac89-6115-21c9-03a9eceefd84_60"
											position={[0.219, -1.75, 0.125]}
										>
											<mesh
												name="Object_122"
												castShadow
												receiveShadow
												geometry={nodes.Object_122.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="78deda1e-83d3-c4ed-6a3e-995b4ecdce66_61"
											position={[0.156, -1.75, 0.125]}
										>
											<mesh
												name="Object_124"
												castShadow
												receiveShadow
												geometry={nodes.Object_124.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="34d24208-4454-1449-cce4-9affc04c1829_62"
											position={[0.094, -1.75, 0.125]}
										>
											<mesh
												name="Object_126"
												castShadow
												receiveShadow
												geometry={nodes.Object_126.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="9af6cfb7-8858-6500-498f-875185b15f22_63"
											position={[0.031, -1.75, 0.125]}
										>
											<mesh
												name="Object_128"
												castShadow
												receiveShadow
												geometry={nodes.Object_128.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="9c33ab27-b53c-a788-4014-7ea4e095b25e_64"
											position={[0.188, 0, 0.063]}
										>
											<mesh
												name="Object_130"
												castShadow
												receiveShadow
												geometry={nodes.Object_130.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="669de06e-7a6f-07c1-2b04-033814255972_65"
											position={[-0.172, 0, 0.063]}
										>
											<mesh
												name="Object_132"
												castShadow
												receiveShadow
												geometry={nodes.Object_132.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="78516a15-677c-fed4-81cf-fe5b2f717150_66"
											position={[0.063, 0, 0.063]}
										>
											<mesh
												name="Object_134"
												castShadow
												receiveShadow
												geometry={nodes.Object_134.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="645bb5d9-c33d-7e1e-b461-89b9832b933f_67"
											position={[0, 0, -0.188]}
										>
											<mesh
												name="Object_136"
												castShadow
												receiveShadow
												geometry={nodes.Object_136.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="16033b20-0a3c-c88b-ac91-408a99462083_68"
											position={[0.188, -0.016, -0.188]}
										>
											<mesh
												name="Object_138"
												castShadow
												receiveShadow
												geometry={nodes.Object_138.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="aacef1f8-f54d-c054-ce12-335cd0707873_69"
											position={[0.109, -0.016, -0.188]}
										>
											<mesh
												name="Object_140"
												castShadow
												receiveShadow
												geometry={nodes.Object_140.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="1b7a0877-1583-3dd4-7f83-4cf1c4d52842_70"
											position={[-0.234, -0.016, -0.188]}
										>
											<mesh
												name="Object_142"
												castShadow
												receiveShadow
												geometry={nodes.Object_142.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="7ed60a0b-7e17-2fc1-2648-f86486e174b3_71"
											position={[-0.172, -0.016, -0.188]}
										>
											<mesh
												name="Object_144"
												castShadow
												receiveShadow
												geometry={nodes.Object_144.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="36e85a0d-7cd9-c0aa-fd36-52629b94774f_72"
											position={[-0.109, -0.016, -0.188]}
										>
											<mesh
												name="Object_146"
												castShadow
												receiveShadow
												geometry={nodes.Object_146.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="7713dbd1-6679-a719-3ca9-a8329eb422c6_73"
											position={[-0.313, -0.016, -0.172]}
										>
											<mesh
												name="Object_148"
												castShadow
												receiveShadow
												geometry={nodes.Object_148.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="75df824b-65b4-5125-fbbb-314eedec5061_74"
											position={[-0.313, -0.141, -0.172]}
										>
											<mesh
												name="Object_150"
												castShadow
												receiveShadow
												geometry={nodes.Object_150.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="2ad8a93b-8e34-3eea-88c8-47f4a683893d_75"
											position={[-0.109, -0.016, 0.078]}
										>
											<mesh
												name="Object_152"
												castShadow
												receiveShadow
												geometry={nodes.Object_152.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="7fed65f2-a909-379d-11f1-6cfc7267ef4d_76"
											position={[0.125, -0.016, 0.078]}
										>
											<mesh
												name="Object_154"
												castShadow
												receiveShadow
												geometry={nodes.Object_154.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="dbac146f-e0fd-0e78-405d-2b0ffba448c9_77"
											position={[-0.109, -0.141, 0.078]}
										>
											<mesh
												name="Object_156"
												castShadow
												receiveShadow
												geometry={nodes.Object_156.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="7bd5bb70-ed32-5c81-d60b-6aeafd1beb11_78"
											position={[-0.109, -0.266, 0.078]}
										>
											<mesh
												name="Object_158"
												castShadow
												receiveShadow
												geometry={nodes.Object_158.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="5c71e30b-cf79-e296-a9c8-5b04f017e09d_79"
											position={[0, -1.625, -0.156]}
										>
											<mesh
												name="Object_160"
												castShadow
												receiveShadow
												geometry={nodes.Object_160.geometry}
												material={materials.material_0}
											/>
										</group>
										<group
											name="tail1_83"
											position={[0.109, -0.681, -0.131]}
											rotation={[-Math.PI / 8, 0, 0]}
										>
											<group
												name="06ab83f7-ffc7-3ea8-8636-a244217de43a_80"
												position={[-0.047, -0.944, -0.025]}
											>
												<mesh
													name="Object_163"
													castShadow
													receiveShadow
													geometry={nodes.Object_163.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="tail2_82"
												position={[0, 0, -0.169]}
												rotation={[-Math.PI / 8, 0, 0]}
											>
												<group
													name="56115dc5-7e23-e549-dee0-62e61bfaff12_81"
													position={[-0.047, -0.944, -0.028]}
												>
													<mesh
														name="Object_166"
														castShadow
														receiveShadow
														geometry={nodes.Object_166.geometry}
														material={materials.material_0}
													/>
												</group>
											</group>
										</group>
										<group
											name="tail3_87"
											position={[0.219, -0.681, 0.134]}
											rotation={[Math.PI / 8, 0, 0]}
										>
											<group
												name="9b892716-1990-16b6-105e-1bee6d49f4c9_84"
												position={[-0.047, -0.944, 0.131]}
											>
												<mesh
													name="Object_169"
													castShadow
													receiveShadow
													geometry={nodes.Object_169.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="tail4_86"
												position={[0, 0, 0.159]}
												rotation={[Math.PI / 8, 0, 0]}
											>
												<group
													name="12333340-a542-6be9-e0d4-9e1aa3afd3d6_85"
													position={[-0.047, -0.944, 0.144]}
												>
													<mesh
														name="Object_172"
														castShadow
														receiveShadow
														geometry={nodes.Object_172.geometry}
														material={materials.material_0}
													/>
												</group>
											</group>
										</group>
										<group
											name="rightArm_111"
											position={[-0.313, -0.125, 0]}
										>
											<group
												name="b98c2885-29d1-5fb0-e85c-37a5dbb270a1_88"
												position={[-0.313, -1.375, 0]}
											>
												<mesh
													name="Object_175"
													castShadow
													receiveShadow
													geometry={nodes.Object_175.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="9a2b193d-563b-bece-1a04-1557fb85d908_89"
												position={[-0.016, 0.125, 0.063]}
											>
												<mesh
													name="Object_177"
													castShadow
													receiveShadow
													geometry={nodes.Object_177.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="3e234acc-3c98-7b16-44e9-34608d51cf22_90"
												position={[0, 0.125, 0.063]}
											>
												<mesh
													name="Object_179"
													castShadow
													receiveShadow
													geometry={nodes.Object_179.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="ea89be14-37df-8566-efec-11659b5f6765_91"
												position={[-0.016, 0.125, 0.063]}
											>
												<mesh
													name="Object_181"
													castShadow
													receiveShadow
													geometry={nodes.Object_181.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="be8257ad-fe50-4e20-cbba-6284734c0530_92"
												position={[-0.016, 0.125, 0.203]}
											>
												<mesh
													name="Object_183"
													castShadow
													receiveShadow
													geometry={nodes.Object_183.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="20dfc787-d603-e302-2dfb-7b0d21946e88_93"
												position={[-0.141, 0.125, 0.063]}
											>
												<mesh
													name="Object_185"
													castShadow
													receiveShadow
													geometry={nodes.Object_185.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="2699972a-ec2b-8f02-eceb-a3cbc2787f1d_94"
												position={[-0.016, 0.078, 0.063]}
											>
												<mesh
													name="Object_187"
													castShadow
													receiveShadow
													geometry={nodes.Object_187.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="4fd1ff5b-2639-286f-afe1-92d15bb0a26e_95"
												position={[-0.016, -0.047, 0.063]}
											>
												<mesh
													name="Object_189"
													castShadow
													receiveShadow
													geometry={nodes.Object_189.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="rightArm1_110"
												position={[0, -0.25, 0]}
											>
												<group
													name="35675072-17a3-19d8-37d6-a4047bb613ac_96"
													position={[-0.313, -1.125, 0]}
												>
													<mesh
														name="Object_192"
														castShadow
														receiveShadow
														geometry={nodes.Object_192.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="18e1d8e7-c632-96db-5fa3-aecd36b0d19b_97"
													position={[0, -0.237, 0.063]}
												>
													<mesh
														name="Object_194"
														castShadow
														receiveShadow
														geometry={nodes.Object_194.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="f9a56fd1-2fb3-e70d-e04e-2b9aaa709548_98"
													position={[0, -0.237, 0.063]}
												>
													<mesh
														name="Object_196"
														castShadow
														receiveShadow
														geometry={nodes.Object_196.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="9a28b786-2c18-2c7d-6b3a-69c1336ae230_99"
													position={[0, -0.284, 0.063]}
												>
													<mesh
														name="Object_198"
														castShadow
														receiveShadow
														geometry={nodes.Object_198.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="3a51f28f-ab9d-5711-b6f9-fcd89960b834_100"
													position={[0, -0.284, 0.063]}
												>
													<mesh
														name="Object_200"
														castShadow
														receiveShadow
														geometry={nodes.Object_200.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="7e351a41-187c-9739-5ca7-6eea09aa6775_101"
													position={[0, -0.331, 0.063]}
												>
													<mesh
														name="Object_202"
														castShadow
														receiveShadow
														geometry={nodes.Object_202.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="e2e5384d-9d39-9767-f479-eca52a0c9b5e_102"
													position={[0, -0.331, 0.063]}
												>
													<mesh
														name="Object_204"
														castShadow
														receiveShadow
														geometry={nodes.Object_204.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="41caff34-fdfd-ee99-ae65-1d3c7dee93e9_103"
													position={[-0.141, -0.237, 0.063]}
												>
													<mesh
														name="Object_206"
														castShadow
														receiveShadow
														geometry={nodes.Object_206.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="1cb22010-c09e-d58e-1afc-80c971818f39_104"
													position={[0, -0.237, 0.203]}
												>
													<mesh
														name="Object_208"
														castShadow
														receiveShadow
														geometry={nodes.Object_208.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="31471572-1810-9ce8-572f-7187a6baba46_105"
													position={[-0.141, -0.284, 0.063]}
												>
													<mesh
														name="Object_210"
														castShadow
														receiveShadow
														geometry={nodes.Object_210.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="8d56eabe-681b-e222-df47-27bb90396070_106"
													position={[0, -0.284, 0.203]}
												>
													<mesh
														name="Object_212"
														castShadow
														receiveShadow
														geometry={nodes.Object_212.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="9e9634f7-1bea-2f9a-dcae-8ba9c99e8db9_107"
													position={[-0.141, -0.331, 0.063]}
												>
													<mesh
														name="Object_214"
														castShadow
														receiveShadow
														geometry={nodes.Object_214.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="a3e262fd-c658-2f1e-9abc-9d53ea5c55a8_108"
													position={[0, -0.331, 0.203]}
												>
													<mesh
														name="Object_216"
														castShadow
														receiveShadow
														geometry={nodes.Object_216.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="a75cfa60-f03c-fff1-b766-1a2df1485890_109"
													position={[0, -0.394, 0.063]}
												>
													<mesh
														name="Object_218"
														castShadow
														receiveShadow
														geometry={nodes.Object_218.geometry}
														material={materials.material_0}
													/>
												</group>
											</group>
										</group>
										<group
											name="leftArm_152"
											position={[0.313, -0.125, 0]}
										>
											<group
												name="9be0786c-ee92-1084-e992-327e91ba89ba_112"
												position={[-0.313, -1.375, 0]}
											>
												<mesh
													name="Object_221"
													castShadow
													receiveShadow
													geometry={nodes.Object_221.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="4efc02bd-0f0c-46f1-7827-9c2ca7f6c1f7_113"
												position={[0.07, 0.092, 0.055]}
												rotation={[-Math.PI / 4, 0, 0]}
											>
												<mesh
													name="Object_223"
													castShadow
													receiveShadow
													geometry={nodes.Object_223.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="d67fc47d-06b7-c4c0-2664-80833e684599_114"
												position={[0.07, 0, -0.039]}
												rotation={[-Math.PI / 8, 0, 0]}
											>
												<mesh
													name="Object_225"
													castShadow
													receiveShadow
													geometry={nodes.Object_225.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="aa111510-3b0b-dd25-a5dd-8933c3edb33d_115"
												position={[0, -0.063, 0.063]}
											>
												<mesh
													name="Object_227"
													castShadow
													receiveShadow
													geometry={nodes.Object_227.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="7a2f2016-af47-8a52-146b-935649434b73_116"
												position={[0, 0.003, 0.203]}
											>
												<mesh
													name="Object_229"
													castShadow
													receiveShadow
													geometry={nodes.Object_229.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="c033c355-e84e-dd75-bf49-af7d066945d3_117"
												position={[-0.141, 0, 0.063]}
											>
												<mesh
													name="Object_231"
													castShadow
													receiveShadow
													geometry={nodes.Object_231.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="d18e3bbb-6673-50d2-4673-1976dd1884e9_118"
												position={[0, -0.063, 0.063]}
											>
												<mesh
													name="Object_233"
													castShadow
													receiveShadow
													geometry={nodes.Object_233.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="83b18342-a892-8216-b441-1de2c83fc46c_119"
												position={[0.07, -0.044, 0.045]}
												rotation={[-Math.PI / 4, 0, 0]}
											>
												<mesh
													name="Object_235"
													castShadow
													receiveShadow
													geometry={nodes.Object_235.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="1553b813-231b-1f82-45d1-ecec868c0a7c_120"
												position={[0.07, -0.028, 0.054]}
												rotation={[-Math.PI / 8, 0, 0]}
											>
												<mesh
													name="Object_237"
													castShadow
													receiveShadow
													geometry={nodes.Object_237.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="da9ec8ed-d862-2f26-a914-d1e02d3d8c16_121"
												position={[0, 0.003, 0.063]}
											>
												<mesh
													name="Object_239"
													castShadow
													receiveShadow
													geometry={nodes.Object_239.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="4f0ea297-3c10-587d-1afc-ac9e379eef50_122"
												position={[-0.141, -0.063, 0.063]}
											>
												<mesh
													name="Object_241"
													castShadow
													receiveShadow
													geometry={nodes.Object_241.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="b06596f0-9cdc-fa4e-62c9-838d4b8aa196_123"
												position={[-0.069, -0.083, 0.07]}
												rotation={[0, 0, -Math.PI / 8]}
											>
												<mesh
													name="Object_243"
													castShadow
													receiveShadow
													geometry={nodes.Object_243.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="831d55a5-5fa2-4c51-b6be-10528ea3dd39_124"
												position={[0, 0.125, 0.063]}
											>
												<mesh
													name="Object_245"
													castShadow
													receiveShadow
													geometry={nodes.Object_245.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="70d776be-e8db-4e4d-733e-835d68658b14_125"
												position={[0, 0.125, 0.063]}
											>
												<mesh
													name="Object_247"
													castShadow
													receiveShadow
													geometry={nodes.Object_247.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="b078e8c7-d5ac-7e05-eb02-786276d302b2_126"
												position={[0, 0.125, 0.063]}
											>
												<mesh
													name="Object_249"
													castShadow
													receiveShadow
													geometry={nodes.Object_249.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="1d4f58b1-bb31-f908-8b81-e060ef6d689f_127"
												position={[0, 0.125, 0.203]}
											>
												<mesh
													name="Object_251"
													castShadow
													receiveShadow
													geometry={nodes.Object_251.geometry}
													material={materials.material_0}
												/>
											</group>
											<group
												name="leftArm1_151"
												position={[0, -0.25, 0]}
											>
												<group
													name="d3c84a47-9b6f-519f-c945-0dbf8d3d9c70_128"
													position={[-0.313, -1.125, 0]}
												>
													<mesh
														name="Object_254"
														castShadow
														receiveShadow
														geometry={nodes.Object_254.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="9fb344bd-9375-4575-5087-98f9239602eb_129"
													position={[0, -0.331, 0.063]}
												>
													<mesh
														name="Object_256"
														castShadow
														receiveShadow
														geometry={nodes.Object_256.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="89fc92e3-b9ec-fdfb-01d5-fb190754e7ec_130"
													position={[0, -0.331, 0.063]}
												>
													<mesh
														name="Object_258"
														castShadow
														receiveShadow
														geometry={nodes.Object_258.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="899048aa-cdb5-1b93-ee0b-32848aaa324e_131"
													position={[0, -0.331, 0.203]}
												>
													<mesh
														name="Object_260"
														castShadow
														receiveShadow
														geometry={nodes.Object_260.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="1db56525-64c5-298b-aad8-238f3bdfa11b_132"
													position={[0, -0.394, 0.063]}
												>
													<mesh
														name="Object_262"
														castShadow
														receiveShadow
														geometry={nodes.Object_262.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="a67c67ce-417e-5ae7-100d-40f730330617_133"
													position={[0, -0.281, 0.063]}
												>
													<mesh
														name="Object_264"
														castShadow
														receiveShadow
														geometry={nodes.Object_264.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="036d08ef-ea25-2e9f-df9a-29a9bca96adc_134"
													position={[0, -0.281, 0.063]}
												>
													<mesh
														name="Object_266"
														castShadow
														receiveShadow
														geometry={nodes.Object_266.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="7f56b489-f44e-2e14-89bb-d6e54312e26f_135"
													position={[0, -0.281, 0.203]}
												>
													<mesh
														name="Object_268"
														castShadow
														receiveShadow
														geometry={nodes.Object_268.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="d0f9b6a9-8a8a-5dfe-06c1-7bd20e568f8b_136"
													position={[0, -0.231, 0.063]}
												>
													<mesh
														name="Object_270"
														castShadow
														receiveShadow
														geometry={nodes.Object_270.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="c7d96b0d-9eb7-0270-a313-4abb74ee3f6a_137"
													position={[0, -0.231, 0.063]}
												>
													<mesh
														name="Object_272"
														castShadow
														receiveShadow
														geometry={nodes.Object_272.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="5ff1790c-8b7a-e66b-ea83-520e96605166_138"
													position={[0, -0.231, 0.203]}
												>
													<mesh
														name="Object_274"
														castShadow
														receiveShadow
														geometry={nodes.Object_274.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="fb25d559-b501-e3c9-e158-61951fc6402a_139"
													position={[-0.141, -0.231, 0.063]}
												>
													<mesh
														name="Object_276"
														castShadow
														receiveShadow
														geometry={nodes.Object_276.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="e7f14c23-c74f-bc60-5fee-702e000568d5_140"
													position={[-0.141, -0.281, 0.063]}
												>
													<mesh
														name="Object_278"
														castShadow
														receiveShadow
														geometry={nodes.Object_278.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="e63e1c1f-82c2-11d5-30e5-dd0f1f3a913e_141"
													position={[-0.141, -0.331, 0.063]}
												>
													<mesh
														name="Object_280"
														castShadow
														receiveShadow
														geometry={nodes.Object_280.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="cdea644e-c65d-31a8-9258-98abdb020cd6_142"
													position={[0, -0.192, 0]}
													rotation={[0, 0, -0.175]}
												>
													<mesh
														name="Object_282"
														castShadow
														receiveShadow
														geometry={nodes.Object_282.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="29b593e8-14b9-e47b-373c-bdde4dbd0b73_143"
													position={[0, -0.192, 0]}
													rotation={[0, 0, -0.175]}
												>
													<mesh
														name="Object_284"
														castShadow
														receiveShadow
														geometry={nodes.Object_284.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="9b1b72e5-5189-9b01-7e3f-10c3c7958f62_144"
													position={[0, -0.192, 0]}
													rotation={[0, 0, -0.175]}
												>
													<mesh
														name="Object_286"
														castShadow
														receiveShadow
														geometry={nodes.Object_286.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="c5de63ff-adbf-a985-5736-fbad3cf9e234_145"
													position={[0, -0.192, 0]}
													rotation={[0, 0, -0.175]}
												>
													<mesh
														name="Object_288"
														castShadow
														receiveShadow
														geometry={nodes.Object_288.geometry}
														material={materials.material_0}
													/>
												</group>
												<group
													name="sword_150"
													position={[-0.016, -0.328, 0]}
												>
													<group
														name="c0e70293-31a1-ae79-f661-2bbccd462b58_146"
														position={[-0.031, -0.047, 0.063]}
													>
														<mesh
															name="Object_291"
															castShadow
															receiveShadow
															geometry={nodes.Object_291.geometry}
															material={materials.material_0}
														/>
													</group>
													<group
														name="a820f387-35c4-b047-9443-b691e9780707_147"
														position={[0, -0.006, 0.142]}
														rotation={[-Math.PI / 8, 0, 0]}
													>
														<mesh
															name="Object_293"
															castShadow
															receiveShadow
															geometry={nodes.Object_293.geometry}
															material={materials.material_0}
														/>
													</group>
													<group
														name="ff32828a-79c4-1bd0-96a0-f5236fb33b2f_148"
														position={[-0.031, -0.047, 0.047]}
													>
														<mesh
															name="Object_295"
															castShadow
															receiveShadow
															geometry={nodes.Object_295.geometry}
															material={materials.material_0}
														/>
													</group>
													<group
														name="61ccac0c-f7fe-2a44-d659-b6aebc5c5bd2_149"
														position={[-0.031, -0.047, -0.25]}
													>
														<mesh
															name="Object_297"
															castShadow
															receiveShadow
															geometry={nodes.Object_297.geometry}
															material={materials.material_0}
														/>
													</group>
												</group>
											</group>
										</group>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('./white_ninja.glb');
